### ISSUE TITLE
When I click on an activity, it shows a pop-up asking if I want to set an alarm

### ISSUE THREAD

**Issue by mattlub** [Heathercoraje/tpilot#9]
- [ ] a user can manually set time for an alarm
- [ ] after a user sets an alarm, it leads to `/'taskname'` 
- [ ] once in `/'taskname` timer starts automatically tracking the time

**Comment by Heathercoraje** [comment]
we have access of taskname through frontend. 
Alarm function/ manual input function has been moved to stretch goal
